# Generated by Django 4.2.7 on 2025-06-05 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_alter_product_options_remove_product_design_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('prompt', models.TextField()),
                ('generated_image_url', models.URLField(max_length=500)),
                ('reference_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('outfit_elements', models.JSONField(blank=True, default=list)),
                ('detected_keywords', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutfitElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fabric', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('design_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='products.designsession')),
            ],
        ),
        migrations.AddIndex(
            model_name='designsession',
            index=models.Index(fields=['user', '-created_at'], name='products_de_user_id_a42a64_idx'),
        ),
        migrations.AddIndex(
            model_name='designsession',
            index=models.Index(fields=['session_id'], name='products_de_session_b3ae4c_idx'),
        ),
    ]
