# Generated by Django 4.2.7 on 2025-06-25 19:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('fabric_type', models.CharField(choices=[('cotton', 'Cotton'), ('silk', 'Silk'), ('wool', 'Wool'), ('linen', 'Linen'), ('polyester', 'Polyester'), ('nylon', 'Nylon'), ('rayon', 'Rayon'), ('denim', 'Denim'), ('jersey', 'Jersey'), ('chiffon', 'Chiffon'), ('twill', 'Twill'), ('canvas', 'Canvas'), ('leather', 'Leather'), ('bamboo', 'Bamboo'), ('modal', 'Modal'), ('crepe', 'Crepe'), ('velvet', 'Velvet'), ('corduroy', 'Corduroy'), ('fleece', 'Fleece'), ('satin', 'Satin')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('cost_per_yard', models.DecimalField(decimal_places=2, max_digits=8)),
                ('premium_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('durability_score', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('comfort_score', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('sustainability_score', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('weight_gsm', models.IntegerField(help_text='Weight in grams per square meter')),
                ('stretch_percentage', models.IntegerField(default=0, help_text='Stretch percentage')),
                ('opacity_percentage', models.IntegerField(default=100, help_text='Opacity percentage')),
                ('care_instructions', models.TextField(blank=True)),
                ('washing_temperature', models.IntegerField(default=30, help_text='Max washing temperature in Celsius')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_sustainable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('minimum_order_yards', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('color_options', models.JSONField(blank=True, default=list)),
                ('pattern_options', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PricingFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_labor_cost', models.DecimalField(decimal_places=2, default=15.0, max_digits=6)),
                ('skilled_labor_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=4)),
                ('overhead_percentage', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('profit_margin_percentage', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('market_demand_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('seasonal_adjustment', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('premium_design_multiplier', models.DecimalField(decimal_places=2, default=1.2, max_digits=4)),
                ('custom_fit_multiplier', models.DecimalField(decimal_places=2, default=1.3, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='outfitelement',
            name='recommended_fabrics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('top', 'Top'), ('tshirt', 'Tshirt'), ('pant', 'Pant'), ('shirt', 'Shirt'), ('jacket', 'Jacker'), ('Hoodie', 'Hoodie')], max_length=50),
        ),
        migrations.CreateModel(
            name='ClothingComplexity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_type', models.CharField(max_length=100)),
                ('base_complexity_score', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('labor_hours', models.DecimalField(decimal_places=2, default=2.0, max_digits=6)),
                ('fabric_yards_needed', models.DecimalField(decimal_places=2, default=2.0, max_digits=6)),
                ('skill_level_required', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=50)),
                ('seam_count', models.IntegerField(default=10)),
                ('button_count', models.IntegerField(default=0)),
                ('zipper_count', models.IntegerField(default=0)),
                ('pocket_count', models.IntegerField(default=0)),
                ('requires_lining', models.BooleanField(default=False)),
                ('requires_interfacing', models.BooleanField(default=False)),
                ('requires_special_tools', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('clothing_type',)},
            },
        ),
        migrations.AddField(
            model_name='outfitelement',
            name='selected_fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.fabric'),
        ),
    ]
